name: 2024_ads-backend

services:

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-prod}
    restart: unless-stopped
    environment:
      - PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - ${APP_PORT}:${APP_PORT}
